### ISSUE TITLE
refactor: simplify trait bounds in chain extension

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-node#102]
The chain extension functions' generic parameters are bounded by traits. This will increase with more future pop api integrations. Perhaps we can just use `Runtime`

**Comment by chungquantin** [comment]
I don't find any problem with this issue as Polkadot SDK also have something like
```rs
impl<C> ChainExtension<C: Config> for ........
```
Where `Config` is the `Config` of the `Runtime`

**Comment by Daanvdplas** [comment]
Correct, this is an old issue
