### ISSUE TITLE
chore: coding guidelines and apply to code.

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-node#105]
- [x] Change CI to `cargo +nightly fmt`. This brings advantages such as formatting comments and dependencies.
- [x] Create coding guidelines in this repo.

EDIT: 
- Replaced the todo's related to pop api to workspace dependencies to a separate issue #206 . 
- Replaced the todo regarding scale inconsistency in #209 

If its already included in your work please continue and we can manage both issues in your PR.

**Comment by evilrobot-01** [comment]
>     * [ ]  pop-api and primitives to workspace dependencies

Need to consider the effects of this when publishing to crates.io

**Comment by Daanvdplas** [comment]
>Need to consider the effects of this when publishing to crates.io

That shouldn't be a problem. Have been working with `ink-sandbox` (crate) and it uses workspace dependencies ([ref](https://github.com/use-ink/ink/blob/master/crates/e2e/sandbox/Cargo.toml))

**Comment by Daanvdplas** [comment]
Close #184
