### ISSUE TITLE
chore: psp22 example contract

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-node#108]
Implement a fungibles contract example implementing the psp22 traits and error provided by the pop api.
- [x] traits implemented and following expected behaviour ([ref](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20))
- [x] `From<StatusCode> for PSP22Error` implementation + tests. For each api there should be one `pallet assets` specific error tested that is converted into `PSP22Error::Custome("<pallet assets error>")`. This is to demonstrate the power of the pop api error.

Using the drink test framework. See internal spec in shortcut.

**Comment by chungquantin** [comment]
Done: https://github.com/r0gue-io/pop-node/pull/300
