### ISSUE TITLE
CI: auto formatter script

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-node#115]
Many parts of this repository is not formatted in the correct way, to reduce the time for development, we should add the auto formatter script to keep the codebase style consistent between contributors. 

The script should run the command `cargo +nightly fmt`

**Comment by Daanvdplas** [comment]
https://github.com/paritytech/polkadot-sdk/blob/d1979d4be9c44d06c62aeea44d30f5f201d67b5e/.github/workflows/checks-quick.yml#L40

**Comment by chungquantin** [comment]
Closed. We agreed to have only format check and let the PR owner to fix it instead of auto formatting.
