### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-node#142]
### Testing
- [x] Build node and test it peers/syncs with testnet parachain: `./target/release/pop-node --chain ./node/chain_specs/pop-paseo.raw.json --base-path <preferred-location> -- --chain ./node/chain_specs/paseo.raw.json --sync warp`
![Screenshot 2024-08-05 at 13 26 55](https://github.com/user-attachments/assets/14afd713-b9b8-4cb4-b431-49e902bbab5f)

 - synced #844277 blocks
 - shown to be peered with collators
- [x] Test runtime upgrade locally (no existing state): 
![Screenshot 2024-08-05 at 14 39 32](https://github.com/user-attachments/assets/e27d5ed5-5009-4911-af5d-7ce4263219b5)

**Pop Network current**
1. Switch to commit of last release and build pop node. This one time two changes have to be made when switched to tag `v0.1.0-alpha2`. Add `paseo.toml` from main to the `networks` folder. In addition, add balances to the chainspec (`node/src/chainspec.rs`):
```
        serde_json::json!({
+                "balances": {
+                    "balances": [],
+                },
                "parachainInfo": {
                        "parachainId": id,
                },
```
* `cargo build --release`

3. Start network with `pop u p -f networks/paseo.toml -R v1.2.5 -v` and:
* verify pop node version -- `rpc calls -> system -> version()`
* verify runtime version -- `rpc calls -> state -> getRuntimeVersion()`

Leave the network running.

**Pop new release**
1. Switch to your branch where you have bumped the versions and rebuild.
2. In Activity Monitor on Mac, find the pop-node process and force quit. The network will still be running, but without the collator so no pop blocks. Or `killall pop-node`.
Return to the terminal where you launched `pop up` and copy the command shown in the output which was used to launch the pop-node collator.
4. In another terminal, run this copied command. This will launch the newly built node (new release) and have it use previously generated chainspecs, effectively allowing it to take over running the network with latest release. Ensure that blocks continue to be produced and verify node version (see above).
5. Upgrade the chain to the new runtime release -- can be found in `target/release/wbuild/testnet_runtime/testnet_runtime.compact.compressed.wasm`
6. Verify successful runtime upgrade:
* verify pop node version -- (see above)
* verify runtime version -- (see above)
* verify migrations have been executed successfully
* verify chain is running

- [x] Test runtime upgrade locally based on existing state from testnet: follow https://github.com/r0gue-io/pop-node/blob/main/.chopsticks/README.md
![Screenshot 2024-08-05 at 18 59 15](https://github.com/user-attachments/assets/815090e6-5639-47eb-9652-418f2bebf21e)

- [x] Test runtime upgrade using `try-runtime`: 
```
cargo b -r --features=try-runtime
try-runtime --runtime ./target/release/wbuild/pop-runtime-testnet/pop_runtime_testnet.wasm on-runtime-upgrade live --uri wss://rpc3.paseo.popnetwork.xyz:433
```
![Screenshot 2024-08-05 at 15 08 01](https://github.com/user-attachments/assets/308f8b61-c794-462f-82df-8a7d2df7435b)

### Release
- [ ] create release for node: e.g. https://github.com/r0gue-io/pop-node/releases/tag/v0.1.0-alpha2
  - [ ] provide a description and then click generate release notes 
- [ ] create release for runtime: e.g. https://github.com/r0gue-io/pop-node/releases/tag/v0.1.0-alpha2
  - [ ] provide a description and then click generate release notes 
- [ ] do a final runtime upgrade with chopsticks using the deterministic runtime wasm blob from the release.
- [ ] approve and enact on chain

**Comment by Daanvdplas** [comment]
Stuck on `try-runtime` and chopsticks tests

**Comment by evilrobot-01** [comment]
See #155 and #157
