### ISSUE TITLE
feat: make drink generic to support pop-api

### ISSUE THREAD

**Issue by Daanvdplas** [r0gue-io/pop-node#251]
We want to offer the developers a test suite for interacting with the pop chain extension. Luckily there is drink!.

# Goal

Create an example contract (preferably with some logic around the api to see how what the devex is like - e.g. `Error`) using drink! for testing.

# Steps

- [x] Fork the drink! repository with the [following changes](https://github.com/Daanvdplas/drink) to make drink! mostly generic.
- [x] Move the required code from [ink sandbox](https://github.com/use-ink/ink/tree/master/crates/e2e/sandbox) (e.g. the `Sandbox trait) to the forked drink repository. This is not dependent of any ink code, see `Cargo.toml`, so this should be straightforward. There are some useful macros that can be used as well.
- [x] Now in the pop-node repo we want to create a `PopSandbox` ([here you can see how](https://github.com/Daanvdplas/fungibles_api_example/blob/main/lib.rs)) which the developers can then use for their drink tests. One thing that I haven't tested yet is including the chain extension. The code says it handles it and there is also an[ example ](https://github.com/Daanvdplas/drink/tree/main/examples)in the drink repository, so this should be doable.
- [x] When this all works we want to implement the example contract. This contract will be a very important exercise. Not only will we test the api, the error handling, the test suite, exposure to ink!, but also will be used for the first resource (most probably tutorial) for the pop api.

**Comment by chungquantin** [comment]
Created a new private repository (will be converted to public later) for pop-drink: https://github.com/r0gue-io/pop-drink
