### ISSUE TITLE
fix: execreturnvalue.data value

### ISSUE THREAD

**Issue by evilrobot-01** [r0gue-io/pop-node#263]
As per the comment thread at https://github.com/r0gue-io/pop-node/pull/240#discussion_r1742824968, an additional byte is prepended to the `ExecReturnValue.data` value returned from the contract via `Contracts::bare_call`. This may be the result wrapped in an `Ok()`, but we need to get to the bottom of it to confirm the reason and adapt accordingly.

**Comment by Daanvdplas** [comment]
https://substrate.stackexchange.com/questions/11765/what-should-data-be-decoded-to-in-execreturnvalue

Confirmed by ink! core devs so we can close
