### ISSUE TITLE
ci(bug): `api-integration-tests` duplicate lang item in crate `sp_io` 

### ISSUE THREAD

**Issue by chungquantin** [r0gue-io/pop-node#313]
Got this error on my local when trying to run the integration-tests of pop-api in `main`. See CI error in other branches that also failed at this job.

**Comment by chungquantin** [comment]
Found a solution for this
```
cargo update staging-xcm --precise 14.1.0
```
But the `Cargo.lock` is included in the `.gitignore`, not sure how to change this yet,

**Comment by evilrobot-01** [comment]
Can you not add/specify the dependency as "=14.1.0"?
